Repository dev-AshishRanjan/Hello-World-starter-project, pull requests merged in 2023-10, with the labels that each got.

#2 hello word kotlin
  Database/HelloWord.kt
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/XS

#3 my details & program added
  CONTRIBUTORS.md
  Database/Hello_World_2k23.cpp
Labels: good first issue, hacktoberfest, size/S

#4 C++ code added
  CONTRIBUTORS.md
  Database/helloWorld.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/S

#5 Added 'hello world' in batch programming language
  CONTRIBUTORS.md
  Database/Hello_World.bat
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/XS

#6 Implementation in C
  CONTRIBUTORS.md
  Database/Hello_World.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/S

#7 Hello World in GO
  CONTRIBUTORS.md
  Database/Hello_World.go
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/S

#8 Create HelloWorld.dart
  Database/HelloWorld.dart
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, size/XS

#10 Hello world program in SQL
  Database/Hello_World.sql
Labels: size/XS

#12 Contribution Added
  CONTRIBUTORS.md
  Database/Hello_World_.py
Labels: hacktoberfest, hacktoberfest-accepted, size/S

#13 Create HelloWorld.rb
  CONTRIBUTORS.md
  Database/HelloWorld.rb
Labels: hacktoberfest, hacktoberfest-accepted, size/S

#14 Create queue.cpp
  queue.cpp
Labels: size/M

#17 Create hello.cpp
  Database/hello.cpp
Labels: size/XS

#18 Create HelloWorld.sc
  Database/HelloWorld.sc
Labels: size/XS

#19 Tesing the new repo
  Database/HelloWorld.cpp
  index.html
Labels: hacktoberfest-accepted, size/S

#20 I (Abhinav) have done the required the contribution as stated
  CONTRIBUTORS.md
  Database/Hello_World_Abhi.cpp
Labels: size/S

#21 Create Hello_World_Hect.py
  Database/Hello_World_Hect.py
Labels: size/XS

#22 My new branch...I have added the Hello world Code in Database
  Database/Hello_World_Abhi.cpp
Labels: size/XS

#23 Hello World program in Rust Language has been added
  CONTRIBUTORS.md
  Database/HelloWorld.rs
Labels: hacktoberfest-accepted, size/S

#24 Added Github_user_name and Hello-World program
  CONTRIBUTORS.md
  Database/hello-World.cpp
Labels: hacktoberfest-accepted, size/S
